name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: HTG-YT
          token: ${{ secrets.GH_TOKEN }}

          template: classic
          config_timezone: Asia/Hong_Kong
          repositories: 120
          
          plugin_code: yes
        
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: "full-year"
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_detail: percentage, lines
          plugin_languages_categories: programming
