name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    permissions:
       contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: lowlighter/metrics@latest
        with:
          output_action: none

          token: ${{ secrets.GH_TOKEN }}

          template: classic
          config_timezone: Asia/Hong_Kong
          repositories: 120
          plugin_activity: yes
          plugin_activity_filter: release,issue,pr,review,star,fork
          plugin_languages: yes
          plugin_traffic: yes
      - run: |
          set +e
          ls -la
          git checkout metrics-renders
          git config user.name ${{ secrets.USERNAME }}
          git config user.email ${{ secrets.EMAIL_STRING }}@users.noreply.github.com
          sudo mv /metrics_renders/* ./
          git add --all
          git commit -m "chore: push metrics"
          git push
