name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}

          template: classic
          config_timezone: Asia/Hong_Kong
          repositories: 120
          plugin_activity: no
          plugin_code: yes
          plugin_habits: yes
          plugin_languages: yes
          plugin_languages_ignored: javascript, html, css, php
          plugin_languages_colors: github
          plugin_lines: yes
          plugin_notable: yes
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_user: HTG_YT
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os, projects
